export const appointments = [
  {
    date: "Sep 16 2023",
    petName: "Messi",
    animal: "perro",
    motive: "",
    comment: "",
  },
  {
    date: "Sep 15 2023",
    petName: "Lionel",
    animal: "perro",
    motive: "",
    comment: "",
  },
  {
    date: "Sep 13 2023",
    petName: "Juan",
    animal: "gato",
    motive: "",
    comment: "",
  },
  {
    date: "Sep 8 2023",
    petName: "Poroto",
    animal: "canario",
    motive: "",
    comment: "",
  },
  {
    date: "Sep 16 2023",
    petName: "Cocho",
    animal: "axolote",
    motive: "",
    comment: "",
  },
  {
    date: "Aug 16 2023",
    petName: "Messi",
    animal: "perro",
    motive: "",
    comment: "",
  },
  {
    date: "Aug 15 2023",
    petName: "Lionel",
    animal: "perro",
    motive: "",
    comment: "",
  },
  {
    date: "Aug 13 2023",
    petName: "Juan",
    animal: "gato",
    motive: "",
    comment: "",
  },
  {
    date: "Aug 8 2023",
    petName: "Poroto",
    animal: "canario",
    motive: "",
    comment: "",
  },
  {
    date: "Aug 16 2023",
    petName: "Cocho",
    animal: "axolote",
    motive: "",
    comment: "",
  },
];
